(()=>{
const C=window.CARDS||[];
const DRIVE=[
"16otOI6UVIdvHJHU6FVsz17gHlejOqwEb","1LqdGeHK7gd6vBYVzS2LkaAjlcg3qsRKn","1GnrCQsUgK3ujJMU9SpYqJFGXG6waxi4H","1i_qNHZI7KYxvePzDTzelYhp7BMX3_z3O","1icyN6W87zeX7Rwoa-8YFjnTEciFhpqps","1WGd_rbRhHJPJFCLY_ptPJ6d2139BecfH","1fcYXdoWHJXqONG0S6Ta5eogE0QwuJgrX","10YnTbBAeGXXZLGRoxJeeyKYmkzFY00ky","1ffcQ0Axcieig086zczFudHD_MfOj2eZb","1uyDZzI-bvZh4_foLio0N26YorxBu9OGA","1G08MV4CpT0oN79EJIloXvnVeYZEPc-ic","1NKTIztxyPfNwJ9dP3uBRn73dqH-tpHCZ","1Ge3Pt0LjxBlBbyX0I1BIgMLD9touk0Kv","1C0onQ8VuaDKQsDsjjW22uaE-SPnUquyD","1JjDAm9VX72hd5LzPKMaxu_rOC6HcPemL","16hUCEf9drvIzvVSxhtNKQ1w6YpJ0b1qw","1rNRt6obyxXrowX674tI6gE0uHY9h8ver","13HZopkjW24sw48jG0CT4o4NZcnjRoohS","1dVkocb4TOb5U-ZtqrAxpXstyq-IIYUmy","12Fnj4OUZtkhK04rLGag2n5lRhiDmTV0b","1I8LzRjSVehHaBy1Acuubx9NGq3t1qpes","19tuNwZePJysu49EG3XIdaLxU5UPcAHIn","1pQE_VHo8YexZMP6STOkZ7BTpkAAqoxHp","143seBWhz05QPtXMLDPlJegMrANvcR754","14NLKUvGOWvdqbYSD-8QhojNWeNMGFamu","1cS1qSjUrJ75CUHMCAvXsAibsn6xiFbk-","18k7nyWhILaWRCgC1BaXhrt3_qtgGqNpO","1qzyP_GU8hBvocHQma_H2HjFwyzqDMnEL","1ZBIAkceT4eVs_z78eLzrIewMnXOggPz2","18VVXmIiHr5_-QSV2dEyvPcBIpfEElB21"
];
const driveURL=id=>`https://drive.google.com/thumbnail?id=${encodeURIComponent(id)}&sz=w1600`;
let mapped=0;
C.forEach(c=>{const i=Number(c&&c.imageIndex);if(!c||!c.image||!Number.isInteger(i)||i<0||i>=DRIVE.length)return;c.imageFallback=c.image;c.image=driveURL(DRIVE[i]);c.imageMode='single';mapped++;});
document.title='ET Unit 01';document.documentElement.dataset.build='v41-clear-single-images';
const h1=document.querySelector('#practice h1');if(h1)h1.textContent='ET Unit 01';
const sub=document.querySelector('#practice .sub');if(sub)sub.textContent='Q001–Q300 • Clear Unit 01 lesson images • Recall practice';
const css=document.createElement('style');css.textContent='.pic{background-color:#fff!important;background-repeat:no-repeat!important;image-rendering:auto!important;filter:none!important;-webkit-filter:none!important;cursor:default!important}.v41bar{display:flex;gap:7px;flex-wrap:wrap;margin-top:10px}.v41bar .btn{flex:1;min-width:150px}.v41hint{font-size:11px;color:#aaa;margin-top:7px;line-height:1.45}';document.head.appendChild(css);
const hero=document.querySelector('#practice .hero');if(hero&&!document.getElementById('v41bar')){const bar=document.createElement('div');bar.id='v41bar';bar.className='v41bar';bar.innerHTML='<button id="installAppV41" class="btn o">📲 Install ET Unit 01</button><button id="fullScreenV41" class="btn">⛶ Full Screen</button>';const hint=document.createElement('div');hint.id='v41hint';hint.className='v41hint';hint.textContent=`✅ ${mapped} image-linked cards: එක් එක් ප්‍රශ්නයට අදාල single image එක question එකත් එක්ක clear ලෙස පෙන්වයි. Image touch කළාම zoom/popup නැහැ.`;const status=document.getElementById('status');(status||hero.firstChild).after(bar,hint)}
let deferred=null;const ib=document.getElementById('installAppV41'),hint=document.getElementById('v41hint');if(ib){if(matchMedia('(display-mode: standalone)').matches||navigator.standalone){ib.textContent='✅ ET Unit 01 Installed';ib.disabled=true}addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e;ib.disabled=false});addEventListener('appinstalled',()=>{deferred=null;ib.textContent='✅ ET Unit 01 Installed';ib.disabled=true});ib.onclick=async()=>{if(deferred){deferred.prompt();await deferred.userChoice;deferred=null}else if(hint)hint.textContent='Chrome ⋮ → Install app / Add to Home screen තෝරන්න.'}}
const fs=document.getElementById('fullScreenV41');if(fs){fs.onclick=async()=>{try{if(!document.fullscreenElement)await document.documentElement.requestFullscreen();else await document.exitFullscreen()}catch{};};document.addEventListener('fullscreenchange',()=>{fs.textContent=document.fullscreenElement?'⤢ Exit Full Screen':'⛶ Full Screen'})}
if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('/sw.js?v=41').catch(()=>{}));
})();
