(()=>{
const C=window.CARDS||[];
const DRIVE=["16otOI6UVIdvHJHU6FVsz17gHlejOqwEb","1LqdGeHK7gd6vBYVzS2LkaAjlcg3qsRKn","1GnrCQsUgK3ujJMU9SpYqJFGXG6waxi4H","1i_qNHZI7KYxvePzDTzelYhp7BMX3_z3O","1icyN6W87zeX7Rwoa-8YFjnTEciFhpqps","1WGd_rbRhHJPJFCLY_ptPJ6d2139BecfH","1fcYXdoWHJXqONG0S6Ta5eogE0QwuJgrX","10YnTbBAeGXXZLGRoxJeeyKYmkzFY00ky","1ffcQ0Axcieig086zczFudHD_MfOj2eZb","1uyDZzI-bvZh4_foLio0N26YorxBu9OGA","1G08MV4CpT0oN79EJIloXvnVeYZEPc-ic","1NKTIztxyPfNwJ9dP3uBRn73dqH-tpHCZ","1Ge3Pt0LjxBlBbyX0I1BIgMLD9touk0Kv","1C0onQ8VuaDKQsDsjjW22uaE-SPnUquyD","1JjDAm9VX72hd5LzPKMaxu_rOC6HcPemL","16hUCEf9drvIzvVSxhtNKQ1w6YpJ0b1qw","1rNRt6obyxXrowX674tI6gE0uHY9h8ver","13HZopkjW24sw48jG0CT4o4NZcnjRoohS","1dVkocb4TOb5U-ZtqrAxpXstyq-IIYUmy","12Fnj4OUZtkhK04rLGag2n5lRhiDmTV0b","1I8LzRjSVehHaBy1Acuubx9NGq3t1qpes","19tuNwZePJysu49EG3XIdaLxU5UPcAHIn","1pQE_VHo8YexZMP6STOkZ7BTpkAAqoxHp","143seBWhz05QPtXMLDPlJegMrANvcR754","14NLKUvGOWvdqbYSD-8QhojNWeNMGFamu","1cS1qSjUrJ75CUHMCAvXsAibsn6xiFbk-","18k7nyWhILaWRCgC1BaXhrt3_qtgGqNpO","1qzyP_GU8hBvocHQma_H2HjFwyzqDMnEL","1ZBIAkceT4eVs_z78eLzrIewMnXOggPz2","18VVXmIiHr5_-QSV2dEyvPcBIpfEElB21"];
const driveURL=id=>`https://drive.google.com/thumbnail?id=${encodeURIComponent(id)}&sz=w1600`;
const atlasPos=i=>`${(i%5)*25}% ${Math.floor(i/5)*20}%`;
const fallback=new Map();let mapped=0;
C.forEach(c=>{const i=Number(c&&c.imageIndex);if(!c||!c.image||!Number.isInteger(i)||i<0||i>=DRIVE.length)return;if(!fallback.has(i))fallback.set(i,{url:c.image,pos:atlasPos(i)});c.imageFallback=c.image;c.image=driveURL(DRIVE[i]);c.imageMode='single';mapped++;});

document.title='ET Unit 01';document.documentElement.dataset.build='v42-full-lesson-premium';
const practiceH1=document.querySelector('#practice h1');if(practiceH1)practiceH1.textContent='ET Unit 01';
const practiceSub=document.querySelector('#practice .sub');if(practiceSub)practiceSub.textContent='Q001–Q300 • Complete Unit 01 lesson • Clear lesson images';

const nav=document.querySelector('.tabs');
if(nav&&!nav.querySelector('[data-tab="lesson"]')){const b=document.createElement('button');b.className='tab';b.dataset.tab='lesson';b.textContent='📖 සම්පූර්ණ පාඩම';nav.appendChild(b);}
const main=document.querySelector('main.app');
if(main&&!document.getElementById('lesson')){const sec=document.createElement('section');sec.id='lesson';sec.className='view lesson-view';sec.innerHTML=window.ETU1_LESSON_HTML||'<div class="lesson-shell"><div class="lesson-section"><h2>පාඩම load වෙමින්…</h2></div></div>';main.appendChild(sec);}

const css=document.createElement('style');css.textContent=`
:root{--o:#ff8a00;--o2:#ffb24d;--panel:#111113;--panel2:#171719;--line:#303034;--soft:#a8a8ad;--paper:#f3f3f4}
body{background:radial-gradient(circle at 18% -5%,#3a2109 0,transparent 28%),radial-gradient(circle at 90% 20%,#1c1208 0,transparent 22%),#080808!important;padding-bottom:90px!important}
.app{max-width:1160px!important;padding:16px!important}
.tabs{display:flex!important;grid-template-columns:none!important;gap:9px!important;overflow-x:auto!important;overscroll-behavior-x:contain;scrollbar-width:none;padding:8px!important;border-radius:20px!important;top:8px!important;background:#0a0a0ceF!important;box-shadow:0 14px 40px #0007!important}.tabs::-webkit-scrollbar{display:none}.tab{flex:1 0 auto!important;min-width:152px!important;min-height:50px!important;padding:0 18px!important;border-radius:14px!important;font-size:13px!important;letter-spacing:.1px}.tab.on{box-shadow:0 8px 24px #ff8a0030!important}
.hero{margin-top:16px!important;padding:20px!important;border-radius:24px!important;background:linear-gradient(145deg,#1b1b1e,#0f0f11)!important;box-shadow:0 18px 50px #0005!important}.hero h1{font-size:24px!important}.sub{font-size:13px!important;line-height:1.6!important;margin-top:7px!important}.ok{margin-top:12px!important;padding:11px 12px!important;border-radius:13px!important}
.baskets{gap:12px!important;margin-top:14px!important}.basket{min-height:118px!important;padding:16px!important;border-radius:21px!important}.stats{gap:10px!important;margin-top:12px!important}.stat{padding:14px!important;border-radius:15px!important}.actions{gap:9px!important;margin-top:12px!important}.btn{min-height:48px!important;border-radius:14px!important;padding:0 15px!important}.chips{gap:8px!important;margin-top:12px!important}.chip{min-height:46px!important;border-radius:13px!important;padding:0 14px!important}
.tool{top:78px!important;padding:12px 0 10px!important}.search{min-height:50px!important;border-radius:15px!important;padding:0 15px!important}.list{gap:14px!important}.qa{padding:18px!important;border-radius:20px!important;background:linear-gradient(145deg,#151518,#101012)!important;box-shadow:0 10px 30px #0003!important}.q{font-size:16.5px!important;line-height:1.75!important;margin-top:10px!important}.ans,.mem{line-height:1.75!important;margin-top:11px!important;padding-top:11px!important}.mem{padding:13px!important;border-radius:14px!important}.pic{margin-top:12px!important;border-radius:17px!important;background-color:#fff!important;background-repeat:no-repeat!important;image-rendering:auto!important;filter:none!important;-webkit-filter:none!important;cursor:default!important}.modal{padding:14px!important}.box{padding:16px!important;border-radius:24px!important}.card{padding:18px!important;border-radius:20px!important}.fliptext{line-height:1.7!important}
.v42bar{display:flex;gap:9px;flex-wrap:wrap;margin-top:12px}.v42bar .btn{flex:1;min-width:170px}.v42hint{font-size:12px;color:#aaa;margin-top:8px;line-height:1.55}
.lesson-view{padding-bottom:42px}.lesson-shell{max-width:1000px;margin:0 auto}.lesson-hero{margin-top:16px;padding:clamp(24px,5vw,46px);border:1px solid #3b3023;border-radius:30px;background:radial-gradient(circle at 90% 0,#5a310f55,transparent 38%),linear-gradient(145deg,#19191c,#0d0d0f);box-shadow:0 24px 70px #0007}.lesson-eyebrow{font-size:11px;font-weight:900;letter-spacing:1.35px;color:var(--o2)}.lesson-hero h1{margin:10px 0 2px;font-size:clamp(28px,6vw,48px);line-height:1.25}.lesson-en{margin:0;color:#bcbcc2;font-weight:750;font-size:14px}.lesson-lead{margin:22px 0 0;font-size:16px;line-height:1.95;color:#e3e3e6;max-width:900px}.lesson-meta{display:flex;flex-wrap:wrap;gap:9px;margin-top:20px}.lesson-meta span{padding:9px 12px;border:1px solid #3b3b40;border-radius:999px;background:#ffffff08;color:#ddd;font-size:12px;font-weight:800}
.lesson-jumps{position:sticky;top:78px;z-index:12;display:flex;gap:8px;overflow-x:auto;scrollbar-width:none;padding:12px 0;margin:8px 0;background:linear-gradient(#080808f4,#080808e8)}.lesson-jumps::-webkit-scrollbar{display:none}.lesson-jumps a{flex:0 0 auto;text-decoration:none;color:#ddd;border:1px solid #35353a;background:#121214;border-radius:999px;padding:10px 14px;font-size:12px;font-weight:850}.lesson-jumps a:hover{border-color:var(--o);color:#fff}
.lesson-section{scroll-margin-top:145px;margin-top:22px;padding:clamp(22px,4vw,38px);border:1px solid #2d2d31;border-radius:28px;background:linear-gradient(145deg,#151517,#0e0e10);box-shadow:0 20px 55px #0004}.section-kicker{display:inline-flex;align-items:center;justify-content:center;min-width:50px;height:34px;padding:0 12px;border-radius:999px;background:var(--o);color:#141414;font-weight:950;font-size:13px}.lesson-section h2{font-size:clamp(24px,4vw,34px);line-height:1.35;margin:12px 0 22px}.lesson-section h3{font-size:21px;line-height:1.45;margin:30px 0 12px;color:#fff}.lesson-section h4{font-size:17px;line-height:1.5;margin:24px 0 10px;color:#ffbd70}.lesson-section p{font-size:16px;line-height:1.95;color:#e1e1e4;margin:12px 0}.lesson-section strong{color:#fff}.definition,.example-box{margin:20px 0;padding:18px 20px;border:1px solid #714319;border-radius:18px;background:linear-gradient(145deg,#2b1a09,#1b1209)}.definition h3{margin:0 0 7px;color:#ffb45a}.definition p,.example-box p{margin:0}.lesson-list{display:grid;gap:9px;margin:14px 0 22px;padding-left:24px}.lesson-list li{padding-left:3px;color:#e5e5e7;line-height:1.8;font-size:15.5px}.lesson-list li::marker{color:var(--o)}
.lesson-table-wrap{overflow:auto;margin:16px 0 28px;border:1px solid #35353a;border-radius:18px;background:#0d0d0f}.lesson-table{width:100%;min-width:720px;border-collapse:collapse}.lesson-table th,.lesson-table td{padding:14px 15px;border-bottom:1px solid #2d2d31;border-right:1px solid #29292d;text-align:left;vertical-align:top;line-height:1.65}.lesson-table th{position:sticky;top:0;background:#24170c;color:#ffbd70;font-size:13px}.lesson-table td{font-size:14px;color:#ddd}.lesson-table tr:last-child td{border-bottom:0}
.lesson-gallery{display:grid;gap:14px;margin:20px 0 30px}.lesson-gallery.two{grid-template-columns:repeat(2,minmax(0,1fr))}.lesson-gallery.three{grid-template-columns:repeat(3,minmax(0,1fr))}.lesson-figure{overflow:hidden;border:1px solid #343438;border-radius:20px;background:#101012;box-shadow:0 14px 35px #0004}.lesson-img{aspect-ratio:4/3;background-color:#fff;background-repeat:no-repeat}.lesson-figure figcaption{padding:10px 12px;color:#cfcfd3;font-size:12px;font-weight:800;text-align:center}
.lesson-feature-grid,.turning-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px;margin:18px 0 28px}.lesson-feature,.turn-card{overflow:hidden;border:1px solid #323237;border-radius:20px;background:#111113}.lesson-feature .lesson-card-img,.turn-card .lesson-card-img{aspect-ratio:16/10;background:#fff no-repeat center}.lesson-feature h4,.turn-card h4{margin:16px 17px 8px;color:#ffb55f}.lesson-feature p,.turn-card p{margin:0;padding:0 17px 18px;font-size:14.5px;line-height:1.8;color:#d8d8dc}.turn-card:not(:has(.lesson-card-img)){padding-top:2px}
.lesson-footer{display:flex;align-items:center;justify-content:space-between;gap:16px;margin:24px 0 0;padding:18px 20px;border:1px solid #303034;border-radius:20px;background:#111113}.lesson-footer div{display:grid;gap:3px}.lesson-footer span{font-size:12px;color:#999}.lesson-footer button{border:1px solid #4a3420;background:#22160b;color:#ffb45a;border-radius:13px;min-height:44px;padding:0 14px;font-weight:850}
@media(max-width:720px){.app{padding:10px!important}.tabs{padding:7px!important}.tab{min-width:145px!important;font-size:12px!important}.hero{padding:17px!important}.stats{grid-template-columns:1fr 1fr!important}.lesson-hero{border-radius:24px;padding:24px 20px}.lesson-lead{font-size:15px;line-height:1.85}.lesson-jumps{top:72px}.lesson-section{padding:22px 18px;border-radius:23px}.lesson-section h2{font-size:24px}.lesson-section h3{font-size:19px}.lesson-section p{font-size:15.5px;line-height:1.9}.lesson-gallery.two,.lesson-gallery.three,.lesson-feature-grid,.turning-grid{grid-template-columns:1fr}.lesson-table th,.lesson-table td{padding:12px}.lesson-footer{align-items:flex-start;flex-direction:column}.lesson-footer button{width:100%}}
`;
document.head.appendChild(css);

function applyBg(el,i){if(!Number.isInteger(i)||i<0||i>=DRIVE.length)return;const f=fallback.get(i);el.style.backgroundImage=f?`url("${driveURL(DRIVE[i])}"),url("${f.url}")`:`url("${driveURL(DRIVE[i])}")`;el.style.backgroundSize=f?'contain,500% 600%':'contain';el.style.backgroundPosition=f?`center,${f.pos}`:'center';el.style.backgroundRepeat='no-repeat';el.style.backgroundColor='#fff';}
function mountLessonImages(){document.querySelectorAll('[data-lesson-image]').forEach(holder=>{const i=Number(holder.dataset.lessonImage),cap=holder.dataset.caption||'Unit 01 පාඩම් රූපය';const fig=document.createElement('figure');fig.className='lesson-figure';const img=document.createElement('div');img.className='lesson-img';img.setAttribute('role','img');img.setAttribute('aria-label',cap);applyBg(img,i);const fc=document.createElement('figcaption');fc.textContent=cap;fig.append(img,fc);holder.replaceWith(fig)});document.querySelectorAll('[data-feature-image],[data-turn-image]').forEach(card=>{const raw=card.dataset.featureImage??card.dataset.turnImage;const i=Number(raw);const img=document.createElement('div');img.className='lesson-card-img';applyBg(img,i);card.prepend(img)});}
mountLessonImages();

const hero=document.querySelector('#practice .hero');if(hero&&!document.getElementById('v42bar')){const bar=document.createElement('div');bar.id='v42bar';bar.className='v42bar';bar.innerHTML='<button id="installAppV42" class="btn o">📲 Install ET Unit 01</button><button id="fullScreenV42" class="btn">⛶ Full Screen</button>';const hint=document.createElement('div');hint.id='v42hint';hint.className='v42hint';hint.textContent=`✅ ${mapped} image-linked questions • 📖 සම්පූර්ණ පාඩම tab එකෙන් 1.1–1.5 පිළිවෙලට අදාල රූප සමඟ කියවන්න පුළුවන්.`;const status=document.getElementById('status');(status||hero.firstChild).after(bar,hint)}
let deferred=null;const ib=document.getElementById('installAppV42'),hint=document.getElementById('v42hint');if(ib){if(matchMedia('(display-mode: standalone)').matches||navigator.standalone){ib.textContent='✅ ET Unit 01 Installed';ib.disabled=true}addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e;ib.disabled=false});addEventListener('appinstalled',()=>{deferred=null;ib.textContent='✅ ET Unit 01 Installed';ib.disabled=true});ib.onclick=async()=>{if(deferred){deferred.prompt();await deferred.userChoice;deferred=null}else if(hint)hint.textContent='Chrome ⋮ → Install app / Add to Home screen තෝරන්න.'}}
const fs=document.getElementById('fullScreenV42');if(fs){fs.onclick=async()=>{try{if(!document.fullscreenElement)await document.documentElement.requestFullscreen();else await document.exitFullscreen()}catch{}};document.addEventListener('fullscreenchange',()=>{fs.textContent=document.fullscreenElement?'⤢ Exit Full Screen':'⛶ Full Screen'})}
const top=document.getElementById('lessonTop');if(top)top.onclick=()=>{document.getElementById('lesson')?.scrollIntoView({behavior:'smooth',block:'start'})};
if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('/sw.js?v=42').catch(()=>{}));
})();
